# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9b8f98d5642bebfc1b4019a4150e685e3175c9793a95f3ef8080ac16ae11ed57f138fd9e346c09ca7dd8d238a9f1c7b439d14ae4dfedff0fe13638e1cbb5f3

test:
  secret_key_base: d70e6ea869550a1015bac6059997f2da5f567078cbd8df41fb7c703afad09fb7ca418fc908ec1dba8be46262bd0a12087fb995d881ae1c357965d05de5f532ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
